### ISSUE TITLE
Retina option does not scale font size when defined

### ISSUE THREAD

**Issue by lmoffereins** [Rydgel/Fake-images-please#12]
Compare [this image](http://fakeimg.pl/200x200/ff0000%2C128/000%2C255/?text=Hello!&font=lobster&font_size=85) with [its retina version](http://fakeimg.pl/200x200/ff0000%2C128/000%2C255/?text=Hello!&font=lobster&font_size=85&retina=1). The font size remains the same, even when the image scales, which, obviously, should not be the case. Can this be fixed?

**Comment by Rydgel** [comment]
@lmoffereins Hello. It should be fixed :)

**Comment by lmoffereins** [comment]
@Rydgel Hi. Since the update, I noticed the text baseline has shifted downwards. See below for the cached version from BEFORE the update(s) and the one AFTER a hard page refresh: 

![image](https://cloud.githubusercontent.com/assets/1798102/8139770/8b2f4bd8-1156-11e5-935a-e9b650083b6a.png) ![image](https://cloud.githubusercontent.com/assets/1798102/8139786/ad4dd702-1156-11e5-813a-28ce0a2874be.png)

This is also the case for the retina version.

**Comment by Rydgel** [comment]
@lmoffereins I had to update the imaging library because of my server being upgraded. Because of that the bug appeared. Don't ask me why but they made it more complicated on this part so I had to get the offset of the font myself and subtract it.
It should be ok for what I see now.

**Comment by Rydgel** [comment]
@lmoffereins Let me know if that's fixed for you. I hate opened tickets.
