### ISSUE TITLE
Status code causes error

### ISSUE THREAD

**Issue by lucasmahle** [Rydgel/Fake-images-please#13]
When I use a lightbox (Colorbox in my case) causes an error because the return status is 301

**Comment by Rydgel** [comment]
@lucasmahle Can you show me some URLs that give 301s?

**Comment by lucasmahle** [comment]
It's weird because using Colorbox, the return is 301, but if I direct access via browser, the return is 200.

Look 301:
![image](https://cloud.githubusercontent.com/assets/6144416/10308448/2f053de8-6c0c-11e5-9ffc-1a1cdfe9de84.png)

And 200:
![image](https://cloud.githubusercontent.com/assets/6144416/10308558/d797f40a-6c0c-11e5-9b9e-9dbe05ba8ee0.png)

**Comment by Rydgel** [comment]
The 2 URLs are actually diffenrent. Notice the "/" at the end in the working scenario.
If your lightbox doesn't support redirects (which it should imo), then be sure to have "final" urls.

For instance replacing "http://fakeimg.pl/310x212" by "http://fakeimg.pl/310x212/" should do the trick.

**Comment by lucasmahle** [comment]
I found the problem "Access-Control-Allow-Origin".
Look:
![image](https://cloud.githubusercontent.com/assets/6144416/10320380/98fcfa50-6c49-11e5-9434-64ac335fe76f.png)

**Comment by Rydgel** [comment]
CORS has been enabled.
