### ISSUE TITLE
Fakeimg.pl is down

### ISSUE THREAD

**Issue by slavikdenis** [Rydgel/Fake-images-please#15]
It seems that the fakeimg.pl is down

**Comment by Rydgel** [comment]
Sorry, I forgot to renew the domain name :(
I put a ticket to my registrar support center, we need to wait.
In the meantime, you can access it through that domain:

`http://fakeimg.us-east-1.elasticbeanstalk.com/`

**Comment by slavikdenis** [comment]
Thank you :)

**Comment by Rydgel** [comment]
Should be back up, sorry everyone.

**Comment by slavikdenis** [comment]
Don't want to create another issue so just gonna ask here. Any ideas why https version doesn't work, or it is just me? Thanks

**Comment by Rydgel** [comment]
Not sure what happened, Cloudflare just deleted the website for no reason.
I recreated the configuration, it might take a few minutes to be back up.

**Comment by slavikdenis** [comment]
Lol? Thanks again tho
