### ISSUE TITLE
Max height / width?

### ISSUE THREAD

**Issue by DaPo** [Rydgel/Fake-images-please#17]
Hi @Rydgel, 

Thank you again and again for this awesome service. I already told you that I'm daily using it but it's nice to say it again.

Anyway I have kind of an issue here. Don't know if that's really an issue but I think you want to hear about it.

http://fakeimg.pl/4000x5000 seems to return a 404. Is there any max values for that?

Thank you!

**Comment by Rydgel** [comment]
@DaPo, Yeah I put max values to prevent a memory denial of service by asking something with height of millions of pixels.

https://github.com/Rydgel/Fake-images-please/blob/master/app/helpers/converters.py#L14

The current max value is 4000 pixels but I can increase it if you think it will be helpful.

**Comment by DaPo** [comment]
Oh, ok. I was wondering if it was a bug or anything.

Nevermind, it's fine for me, I was testing a situation where I needed a big ass image, 4000x4000 will do the trick for me.

Thank you for your answer!

Cheers mate.
