### ISSUE TITLE
Allow changing image type via query string

### ISSUE THREAD

**Issue by Gasol** [Rydgel/Fake-images-please#18]
I needs different image type for acceptance test, After digging into the code, Currently, It's only support PNG image.

https://github.com/Rydgel/Fake-images-please/blob/master/app/main.py#L62
https://github.com/Rydgel/Fake-images-please/blob/master/app/helpers/fakeimg.py#L65

**Comment by Rydgel** [comment]
I'll try to find time to do this.

**Comment by JordyMoos** [comment]
I added support for this here: https://github.com/Rydgel/Fake-images-please/pull/35
