### ISSUE TITLE
Allow to use russian text

### ISSUE THREAD

**Issue by n-osennij** [Rydgel/Fake-images-please#19]
Blank image 

`https://fakeimg.pl/150x150/ffffff,128/000,255/?text=Привет`

**Comment by Rydgel** [comment]
Good idea, we will need a font to display cyrillic alphabet, like the Noto font we use for asian languages. Do you know a good one, with no copyrights?

**Comment by Rydgel** [comment]
@n-osennij Actually seems like the Noto font also works with russian.
Take a look:

![](https://fakeimg.pl/150x150/ffffcc,128/000,255/?text=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82&font=noto)
