### ISSUE TITLE
Add line break

### ISSUE THREAD

**Issue by jc7447** [Rydgel/Fake-images-please#20]
Hi,

Is there a way to add a line break in text ? I tried : 

https://fakeimg.pl/350x200/?text=Hello\nthere (not interpreted) 
https://fakeimg.pl/350x200/?text=Hello&#10;there  ('there' disappear)

Thanks

**Comment by seven017438** [comment]
Hi, 
I used the link https://fakeimg.pl ,and browser showed me "DNS_PROBE_FINISHED_NXDOMAIN"

did I get some wrong?

**Comment by IRediTOTO** [comment]
Yes, me too.

**Comment by Jogai** [comment]
Use %0A

Example https://fakeimg.pl/1440x180/282828/eae0d0/?text=%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%80%81%E3%83%BD%E3%80%81%E3%83%BD%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%80%81%0A%EF%BD%80%E3%83%BD%EF%BD%80(((((%20(%20%E2%8A%83%E3%83%BB%CF%89%E3%83%BB)%E2%8A%83%E2%98%82%EF%BD%80(%C2%B4%CF%89%EF%BD%80u)))%E3%83%BD%EF%BD%80%E3%80%81%0A%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%80%81%E3%83%BD%E3%80%81%E3%83%BD%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%80%81&font=noto

**Comment by IRediTOTO** [comment]
> Use %0A
> 
> Example https://fakeimg.pl/1440x180/282828/eae0d0/?text=%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%80%81%E3%83%BD%E3%80%81%E3%83%BD%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%80%81%0A%EF%BD%80%E3%83%BD%EF%BD%80(((((%20(%20%E2%8A%83%E3%83%BB%CF%89%E3%83%BB)%E2%8A%83%E2%98%82%EF%BD%80(%C2%B4%CF%89%EF%BD%80u)))%E3%83%BD%EF%BD%80%E3%80%81%0A%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%80%81%E3%83%BD%E3%80%81%E3%83%BD%EF%BD%80%E3%83%BD%EF%BD%80%E3%80%81%E3%83%BD%EF%BD%80%E3%80%81&font=noto

You are amazingggggggggggg

**Comment by IRediTOTO** [comment]
@Jogai  what did you use to create that ?

**Comment by Rydgel** [comment]
That's amazing, I didn't know you could do that!

**Comment by Jogai** [comment]
Used urlencoding and google for kamoji ( ͡° ͜ʖ ͡°)
