### ISSUE TITLE
Fakeimg x srcset results in a mixed-content error

### ISSUE THREAD

**Issue by DaPo** [Rydgel/Fake-images-please#22]
Hi @Rydgel,

Long time no see!

I think I may have an issue with fakeimg & srcset attribut on an IMG element as you can [see here](https://codepen.io/CyrilKrylatov/pen/oNgywWw). With Firefox 73.0b3 Developer Edition I have a [mixed content security](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) issue.

Do you have any clue on what's happening there?

If I remove the `srcset` attribute on my Codepen, I don't have any error.

Cheers!

**Comment by Rydgel** [comment]
Might be related to the URL redirection when there is no trailing slash.
Try to add it at the end of the URLs and tell me if it works better

**Comment by DaPo** [comment]
Oh yeah nice catch, it works! Thank you. 🙏 

All the best for this new year, hope you're fine.

See you!
