### ISSUE TITLE
I guess the domain is down again :) 

### ISSUE THREAD

**Issue by mmorisset** [Rydgel/Fake-images-please#23]
The domain is down again (same date as this issue: https://github.com/Rydgel/Fake-images-please/issues/15)

**Comment by bin16** [comment]
2 days later, nothing changed. `fakeimg.pl` is my favorite tool to generate some image, especially with words.

**Comment by Rydgel** [comment]
I contacted my registrar service, seems like there is a bug in the dashboard because I can't see the domain listed 🤕

**Comment by bin16** [comment]
![](https://fakeimg.pl/300x200/7ef/39a/?text=(%20%20%20%E2%80%A2_%E2%80%A2)%20ok)

**Comment by Rydgel** [comment]
Should be up
