### ISSUE TITLE
This specific text causes a 500 error

### ISSUE THREAD

**Issue by eladiosch** [Rydgel/Fake-images-please#26]
Hi, big fan of this project. But the weirdest thing is happening to me. 

This is causing an Internal Server Error
https://fakeimg.pl/100x100/?text=PruebaActivoNuevaUnidad

But only with that specific text and size. If I change one letter or one pixel, it works.

Anyways, it isn't a big problem for me, but I thought it was worth pointing out.

Cheers

**Comment by Rydgel** [comment]
Hi 👋 
It works for me, seems like a bad caching response issue

**Comment by eladiosch** [comment]
Yep, it was working like 1 hour after I opened the issue, but it keeps happening kind of randomly. 

For example, these two are not working right now:

https://fakeimg.pl/80x80/?text=Acelerador%20Contacto
https://fakeimg.pl/80x80/?text=Framework

But other similar images are working correctly, so no idea what triggers those errors
