### ISSUE TITLE
got 'Internal Server Error' error

### ISSUE THREAD

**Issue by raylhx** [Rydgel/Fake-images-please#27]
hi,
link: https://fakeimg.pl/150x200/?text=Helloooo

but,just got the error like this:

**Status Code: 500** 

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I think may be the font is cause of this error.

**Comment by Rydgel** [comment]
I had some issues with Cloudflare, can you tell me if it's better now? 
I changed some settings.

**Comment by raylhx** [comment]
It's okay now ! 
link: https://fakeimg.pl/150x200/?text=Helloooo
