### ISSUE TITLE
Server error with some image sizes

### ISSUE THREAD

**Issue by vikfx** [Rydgel/Fake-images-please#28]
Hi,

I encountered errors with certain valid url. 
For example : [https://fakeimg.pl/700x800/](https://fakeimg.pl/700x800/) return a server error
but [https://fakeimg.pl/800x700/](https://fakeimg.pl/800x700/) works

[https://fakeimg.pl/800x800/?text=remplace](https://fakeimg.pl/800x800/?text=remplace) work but not [https://fakeimg.pl/800x700/?text=fakeimg](https://fakeimg.pl/800x700/?text=fakeimg)

I haven't dicerned any pattern.

**Comment by Rydgel** [comment]
Hi @vikfx , let me look.

**Comment by Rydgel** [comment]
I had some issues with Cloudflare, can you tell me if it's better now?
I changed some settings.

**Comment by vikfx** [comment]
Looks like everything works fine now.
Thanks and sorry for the delay I don't come often on github. ;)

**Comment by Rydgel** [comment]
No problem :)
Glad it works now.
