### ISSUE TITLE
Add emoji on fake image

### ISSUE THREAD

**Issue by ivanindoleads** [Rydgel/Fake-images-please#29]
Hi,

Is there a way to add an emoji in the text? I tried :

https://fakeimg.pl/350x200/?text=Hello❤️

Thanks

**Comment by Rydgel** [comment]
I think I found a way, I'm working on it

**Comment by Rydgel** [comment]
![https://fakeimg.pl/440x230/282828/eae0d0/?retina=1&text=Supports%20emojis!%20%F0%9F%98%8B](https://fakeimg.pl/440x230/282828/eae0d0/?retina=1&text=Supports%20emojis!%20%F0%9F%98%8B)
